// Human-readable ABIs. Custom errors are included so ethers can decode reverts into names that
// src/web3/errors.ts turns into friendly messages.

const COMMON_ERRORS = [
  'error EnforcedPause()',
  'error ExpectedPause()',
  'error OwnableUnauthorizedAccount(address account)',
  'error ReentrancyGuardReentrantCall()',
  'error ZeroAddress()',
  'error ERC20InsufficientBalance(address sender, uint256 balance, uint256 needed)',
  'error ERC20InsufficientAllowance(address spender, uint256 allowance, uint256 needed)',
  'error ERC721IncorrectOwner(address sender, uint256 tokenId, address owner)',
  'error ERC721InsufficientApproval(address operator, uint256 tokenId)',
  'error ERC721NonexistentToken(uint256 tokenId)',
];

export const TOKEN_ABI = [
  'function name() view returns (string)',
  'function balanceOf(address account) view returns (uint256)',
  'function allowance(address owner, address spender) view returns (uint256)',
  'function approve(address spender, uint256 amount) returns (bool)',
  'function nonces(address owner) view returns (uint256)',
  'function totalSupply() view returns (uint256)',
  'function MAX_SUPPLY() view returns (uint256)',
  'function eip712Domain() view returns (bytes1 fields, string name, string version, uint256 chainId, address verifyingContract, bytes32 salt, uint256[] extensions)',
  'error MaxSupplyExceeded(uint256 requested, uint256 available)',
  'error AccessControlUnauthorizedAccount(address account, bytes32 neededRole)',
  ...COMMON_ERRORS,
];

export const NFT_ABI = [
  'function owner() view returns (address)',
  'function paused() view returns (bool)',
  'function mintPrice() view returns (uint256)',
  'function nextEggId() view returns (uint256)',
  'function totalMinted() view returns (uint256)',
  'function MAX_EGGS_PER_TX() view returns (uint256)',
  'function HATCH_WINDOW() view returns (uint256)',
  'function tokensOfOwner(address owner) view returns (uint256[] ids, uint256[] speeds)',
  'function pendingEggsOf(address owner) view returns (uint256[] eggIds, uint256[] commitBlocks)',
  'function isApprovedForAll(address owner, address operator) view returns (bool)',
  'function setApprovalForAll(address operator, bool approved)',
  'function buyEggs(uint256 quantity) payable returns (uint256 firstEggId)',
  'function hatchEggs(uint256[] eggIds)',
  'function setMintPrice(uint256 newPrice)',
  'function withdraw(address to)',
  'function pause()',
  'function unpause()',
  'event EggsPurchased(address indexed buyer, uint256 firstEggId, uint256 quantity, uint256 paid)',
  'event EggHatched(uint256 indexed eggId, address indexed owner, uint256 indexed tokenId, uint256 speed, bool expired)',
  'error InvalidQuantity()',
  'error InsufficientPayment(uint256 required, uint256 sent)',
  'error UnknownEgg(uint256 eggId)',
  'error EggNotReady(uint256 eggId)',
  'error InvalidSpeed(uint256 speed)',
  'error InvalidPrice()',
  'error NothingToWithdraw()',
  ...COMMON_ERRORS,
];

export const FARM_ABI = [
  'function owner() view returns (address)',
  'function paused() view returns (bool)',
  'function rewardRate() view returns (uint256)',
  'function MAX_REWARD_RATE() view returns (uint256)',
  'function MAX_BATCH() view returns (uint256)',
  'function totalSpeedStaked() view returns (uint256)',
  'function totalStaked() view returns (uint256)',
  'function getUserInfo(address account) view returns (uint256[] tokenIds, uint256[] speeds, uint256 totalSpeed, uint256 pending, uint256 rewardPerSecond)',
  'function stake(uint256[] tokenIds)',
  'function withdraw(uint256[] tokenIds)',
  'function emergencyWithdraw(uint256[] tokenIds)',
  'function claimAll()',
  'function setRewardRate(uint256 newRate)',
  'function pause()',
  'function unpause()',
  'event RewardClaimed(address indexed user, uint256 reward)',
  'error EmptyBatch()',
  'error BatchTooLarge(uint256 size, uint256 max)',
  'error NotStaker(uint256 tokenId)',
  'error ZeroSpeed(uint256 tokenId)',
  'error RateTooHigh(uint256 rate, uint256 max)',
  'error NothingToClaim()',
  'error MaxSupplyExceeded(uint256 requested, uint256 available)',
  'error AccessControlUnauthorizedAccount(address account, bytes32 neededRole)',
  ...COMMON_ERRORS,
];

export const STAKING_ABI = [
  'function owner() view returns (address)',
  'function paused() view returns (bool)',
  'function getPlans() view returns (uint8[] months, uint256[] aprs)',
  'function rewardPool() view returns (uint256)',
  'function totalStaked() view returns (uint256)',
  'function totalRewardsReserved() view returns (uint256)',
  'function activeStakes() view returns (uint256)',
  'function stakedByPeriod(uint8 lockMonths) view returns (uint256)',
  'function getActiveStakes(address user) view returns (uint256[] stakeIds, uint256[] amounts, uint256[] startTimes, uint256[] endTimes, uint256[] lockMonths, uint256[] rewards)',
  'function stake(uint256 amount, uint8 lockMonths) returns (uint256)',
  'function stakeWithPermit(uint256 amount, uint8 lockMonths, uint256 deadline, uint8 v, bytes32 r, bytes32 s) returns (uint256)',
  'function unstake(uint256 stakeId)',
  'function unstakeMany(uint256[] stakeIds)',
  'function fundRewards(uint256 amount)',
  'function withdrawRewardPool(uint256 amount, address to)',
  'function setPlan(uint8 lockMonths, uint256 newAprBps)',
  'function pause()',
  'function unpause()',
  'event Staked(address indexed user, uint256 indexed stakeId, uint256 amount, uint256 lockMonths, uint256 reward, uint256 endTime)',
  'event Unstaked(address indexed user, uint256 indexed stakeId, uint256 principal, uint256 reward)',
  'error ZeroAmount()',
  'error InvalidPlan(uint8 lockMonths)',
  'error InvalidLockPeriod(uint8 lockMonths)',
  'error AprTooHigh(uint256 aprBps, uint256 max)',
  'error StakeNotFound(uint256 stakeId)',
  'error AlreadyWithdrawn(uint256 stakeId)',
  'error StillLocked(uint256 stakeId, uint256 endTime)',
  'error InsufficientRewardPool(uint256 required, uint256 available)',
  ...COMMON_ERRORS,
];
